### ISSUE TITLE
Simple DOT graph causes unhandled NotImplementedException: Unsupported node type: AttributeBegin

### ISSUE THREAD

**Issue by konste** [timepp/dot2dgml#2]
I have generated very small Graph.DOT file (attached) and dot tools render it just fine. 
[graph.zip](https://github.com/timepp/dot2dgml/files/3933184/graph.zip)
Unfortunately when I try to open it with your Plainion.GraphViz-3.3  Viewer it immediately blows up with the exception: 
```---------------------------
Unhandled exception
---------------------------
 System.NotImplementedException: Unsupported node type: AttributeBegin

 Context: 

   System.Object: 

 StackTrace:    at Plainion.GraphViz.Modules.Documents.DotLang.Parser.Parse()

   at Plainion.GraphViz.Modules.Documents.DotLangDocument.Read(TextReader reader)

   at Plainion.GraphViz.Modules.Documents.DotLangDocument.Load()

   at Plainion.GraphViz.Modules.Documents.AbstractGraphDocument.Load(String path)

   at Plainion.GraphViz.Modules.Documents.BasicDocumentProcessor.<LoadDocuments>d__14.MoveNext()

   at Plainion.GraphViz.Modules.Documents.BasicDocumentProcessor.Process(String path)

   at Plainion.GraphViz.Modules.Documents.OpenDocumentsViewModel.OpenDocument(String path)

   at Plainion.GraphViz.Modules.Documents.OpenDocumentsViewModel.Open(String path)

   at Plainion.GraphViz.Modules.Documents.OpenDocumentsViewModel.<OpenDocument>b__19_0(OpenFileDialogNotification n)

   at Prism.Interactivity.InteractionRequest.InteractionRequest`1.<>c__DisplayClass4_0.<Raise>b__0()

   at Plainion.Prism.Interactivity.PopupCommonDialogAction.Invoke(Object parameter)

   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)

   at System.Windows.Interactivity.EventTriggerBase.OnEvent(EventArgs eventArgs)

   at System.Windows.Interactivity.EventTriggerBase.OnEventImpl(Object sender, EventArgs eventArgs)

   at Prism.Interactivity.InteractionRequest.InteractionRequest`1.Raise(T context, Action`1 callback)

   at Plainion.GraphViz.Modules.Documents.OpenDocumentsViewModel.OpenDocument()

   at Prism.Commands.DelegateCommand.Execute()

   at Prism.Commands.DelegateCommand.Execute(Object parameter)

   at Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.Execute(Object parameter)

   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)

   at System.Windows.Controls.Primitives.ButtonBase.OnClick()

   at System.Windows.Controls.Button.OnClick()

   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)

   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)

   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


---------------------------
OK   
---------------------------
```

I have a lot of hopes for your Plainion.GraphViz-3.3 Viewer and wonder if you could look into fixing it. 

Thank you!
Konstantin

**Comment by timepp** [comment]
Hi Konstantin,

Don't know about "Plainion.GraphViz-3.3" but this is "dot2dgml". For the dot file you attached, I successfully convert&opened it in visual studio (see attached image) with some change on "dot2dgml" (now v1.02). 

Hope that helps. 
![2020-01-04 143142](https://user-images.githubusercontent.com/75576/71760870-f9753380-2efe-11ea-9522-1341ae321142.png)

**Comment by konste** [comment]
Thanks a lot, @timepp! Your version 1.02 works almost perfectly. The only gripe I have is that to every DGML graph it generates it adds four standalone nodes for "{", "}", "node" and "graph".  On the picture above you can see them in the lower left corner. Why is that? Could you please make **dot2dgml** not to add those? Direct .dot visualizers I tried do not show those standalone nodes.

**Comment by timepp** [comment]
done in v1.03, please try it out

**Comment by konste** [comment]
Tried 1.03 - standalone nodes for curly braces are gone! This is good. Other two disconnected nodes for "node" and "graph" are still there. Tiny graph.dot and resulting graph.dgml attached.

[graph.zip](https://github.com/timepp/dot2dgml/files/4031709/graph.zip)

**Comment by timepp** [comment]
Yes this was some work included in my next refactor of more accurate parser. please re-download 1.03 and have a try

**Comment by konste** [comment]
@timepp It works beautifully! I wish everybody is that responsive and helpful as you are! Thanks a lot!
